### PR TITLE
Channel Whitelisting, Name Lowercase Cast & Alolan Pokemon

### PR DESCRIPTION
**Pull request by Katsulynx**
Added Channel Whitelisting
Added Alolan Forms
Added Name to Lowercase Cast for Catch Commands

### CODE REVIEW

**Comment by Myth-26** [comment]
alolan meowth is mistaken for forretrres

**Comment by Mewzer** [comment]
most of the alolans are wrong

**Comment by Katsulynx** [comment]
I've used the Bulbapedia images as mentioned in a few other PRs/issues. I've found that using the images from p!info <name> lead to an accuracy of 0.99.

**Comment by devadula-nandan** [comment]
can someone tell how can i new pokemons to the poke.json

**Comment by sbernardbrousseau** [comment]
how do i had this to the base branch ?

**Comment by dawqf** [comment]
@Katsulynx how can i compile your pull request?

**Comment by hyquoccuong** [comment]
To use hastool:
- Dowload HashTool.zip here https://github.com/ExtraConcentratedJuice/pokecord-catcher/releases
- Unzip to get publish folder
- Download, install the .NET Core runtime from [HERE](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.1-windows-hosting-bundle-installer)
- Enter folder publish
- Create a folder name Pokemon (or anything else), and copy image of pokemons which you want to update(eg: Alolan Pokemons), name those images by exact pokemon names in Pokecord(Eg: Alolan Meowth.png)
- Back to folder public hold shift and right click, then choose open PowerShell
- Run command **dotnet HashTool.dll**, when you got message **Enter a path to the directory of Pokemon that you want to hash:**, input the name of folder contains new pokemon images then hit enter
- Wait for script run, hash and generate pokemon code, after it finish, you will see file poke.json in publish folder, open it and update new content to poke.json in bot folder (You should use code editor to compare 2 json files and merge them)

Porblem here is where to get poke mon images that Pokecord can accept :)

**Comment by Orange65** [comment]
> Added Channel Whitelisting
> Added Alolan Forms
> Added Name to Lowercase Cast for Catch Commands
Is there anyway I can add this to my bot?


> @atasheep
> 
> To use hastool:
> 
> * Dowload HashTool.zip here https://github.com/ExtraConcentratedJuice/pokecord-catcher/releases
> * Unzip to get publish folder
> * Download, install the .NET Core runtime from [HERE](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.1-windows-hosting-bundle-installer)
> * Enter folder publish
> * Create a folder name Pokemon (or anything else), and copy image of pokemons which you want to update(eg: Alolan Pokemons), name those images by exact pokemon names in Pokecord(Eg: Alolan Meowth.png)
> * Back to folder public hold shift and right click, then choose open PowerShell
> * Run command **dotnet HashTool.dll**, when you got message **Enter a path to the directory of Pokemon that you want to hash:**, input the name of folder contains new pokemon images then hit enter
> * Wait for script run, hash and generate pokemon code, after it finish, you will see file poke.json in publish folder, open it and update new content to poke.json in bot folder (You should use code editor to compare 2 json files and merge them)
> 
> Porblem here is where to get pokemon images that Pokecord accept them :)
Has anyone already hashed all the pokemon? If not I'll upload it here once I've done it..

**Comment by hyquoccuong** [comment]
@Orange65 
Here click Raw and copy content and paste to your file
https://github.com/ExtraConcentratedJuice/pokecord-catcher/blob/d7fe3d1f9d65116a562018c8a7b175845d875ba0/Assets/poke.json

**Comment by Orange65** [comment]
> @Orange65
> Here click Raw and copy content and paste to your file
> https://github.com/ExtraConcentratedJuice/pokecord-catcher/blob/d7fe3d1f9d65116a562018c8a7b175845d875ba0/Assets/poke.json

Yes I managed to figure out how to do this a few days ago, thank you anyway

**Comment by VNRG1993** [comment]
> 
> 
> @Orange65
> Here click Raw and copy content and paste to your file
> https://github.com/ExtraConcentratedJuice/pokecord-catcher/blob/d7fe3d1f9d65116a562018c8a7b175845d875ba0/Assets/poke.json

ty! you are a saviour

**Comment by VNRG1993** [comment]
the code still need some tweaks cuz instead of "alolan meowth" the bot tried to catch it as "forretress" still and failed, would be cool if anyone could solve this problem and maybe other alolan forms are bugged as well, ty in advance

so far buggy ones:
- alolan meowth was mistaken as forretress
- alolan rattata was mistaken as suicune
- alolan ratticate mistaken as flaaffy

not buggy but not 100% accuracy
- alolan grimer was caught successfully but didnt have a similarity of 1 (was 0.942....... instead)

**Comment by C0L0R** [comment]
@Katsulynx How do I use this updated feature? I need that lowercase feature.

**Comment by jjmsonic** [comment]
I hashed out all the alolans that weren't working, and it still mistakes them. Any fixes? And yes I'm using the latest poke.json off of here.

**Comment by ModFatherOG** [comment]
just ran into the issue of pokecord not accepting the name while having the first letter Capitalized so i went thru and made them all lowercase in the Poke.json. if anyone else needs it here it is, just rename to ".json" and replace old file.
[poke.txt](https://github.com/ExtraConcentratedJuice/pokecord-catcher/files/3140103/poke.txt)

**Comment by IdontKnowMuchAtAll** [comment]
in case anyone doesn't have the new temporary detective pikachu, this hash works for me

"Detective Pikachu":["0x67E2E10050B5FEA67C62A83168491A5D3F5A6F676A6062566561806E74726B78646A625F615B6862"]

**Comment by ModFatherOG** [comment]
i just renamed "munchlax" in the poke.json file as it was the one the bot
thought most resembled the hash by .79% so now its been working every time

**Comment by AdityaSoni25** [comment]
> in case anyone doesn't have the new temporary detective pikachu, this hash works for me
> 
> "Detective Pikachu":["0x67E2E10050B5FEA67C62A83168491A5D3F5A6F676A6062566561806E74726B78646A625F615B6862"]

Thanks a lot.

**Comment by AdityaSoni25** [comment]
Does anyone know how to add multiple channel IDs for spamming? I want to target multiple private servers.

**Comment by wedus19** [comment]
detective pikachu is not working for me

**Comment by IdontKnowMuchAtAll** [comment]
As a lot of alolans werent working for me I decided to rehash some of them, here is my updated poke.json file (it's in a .zip because you can't add a .json to comments). If any pokemons don't work for you using this file please tell me so i can change it asap.
[poke.zip](https://github.com/ExtraConcentratedJuice/pokecord-catcher/files/3172359/poke.zip)

**Comment by VNRG1993** [comment]
I have managed to fix most of the issues of the poke.json file, check here:

https://github.com/ExtraConcentratedJuice/pokecord-catcher/issues/151

**Pull request merged**
